export const CONFIG = {
  buildTag: "dv-174-motion-controls-and-truth",
  devControls: {
    enabled: true,
  },
  modes: {
    names: {
      1: "Liquid Tie-Dye",
      2: "Mandala Bloom Fractal",
      3: "Liquid Tie-Dye (3)",
      4: "Liquid Tie-Dye (4)",
    },
    defaultMode: 1,
    autoCycleSeconds: 18,
    settingsByMode: {
      1: {
        micSensitivity: 2.0,
        noiseGate: 0.02,
        sustainThreshold: 0.03,
        activateThreshold: 0.05,
        deactivateThreshold: 0.02,
        holdTime: 650,
        fadeTime: 900,
        motionScale: 0.08,
        baseFlow: 0.0,
        responseCurve: 1.15,
        maxSpeed: 0.18,
        audioReactivity: 1.0,
        peakIntensity: 1.0,
        bassWeight: 1.0,
        midsWeight: 0.9,
        highsWeight: 0.65,
      },
      2: {
        micSensitivity: 2.0,
        noiseGate: 0.02,
        sustainThreshold: 0.03,
        activateThreshold: 0.05,
        deactivateThreshold: 0.02,
        holdTime: 650,
        fadeTime: 900,
        motionScale: 0.05,
        baseFlow: 0.0,
        responseCurve: 1.15,
        maxSpeed: 0.12,
        audioReactivity: 1.0,
        peakIntensity: 1.0,
        bassWeight: 1.0,
        midsWeight: 0.9,
        highsWeight: 0.65,
      },
      3: {
        micSensitivity: 2.0,
        noiseGate: 0.02,
        sustainThreshold: 0.03,
        activateThreshold: 0.05,
        deactivateThreshold: 0.02,
        holdTime: 650,
        fadeTime: 900,
        motionScale: 0.07,
        baseFlow: 0.0,
        responseCurve: 1.15,
        maxSpeed: 0.16,
        audioReactivity: 1.0,
        peakIntensity: 1.0,
        bassWeight: 1.0,
        midsWeight: 0.9,
        highsWeight: 0.65,
      },
      4: {
        micSensitivity: 2.0,
        noiseGate: 0.02,
        sustainThreshold: 0.03,
        activateThreshold: 0.05,
        deactivateThreshold: 0.02,
        holdTime: 650,
        fadeTime: 900,
        motionScale: 0.1,
        baseFlow: 0.0,
        responseCurve: 1.15,
        maxSpeed: 0.2,
        audioReactivity: 1.0,
        peakIntensity: 1.0,
        bassWeight: 1.0,
        midsWeight: 0.9,
        highsWeight: 0.65,
      },
    },
  },

  soloEvents: {
    enabled: false,
    baseSpawnChance: 0.015,
    cooldownSeconds: {
      min: 8,
      max: 18,
    },
    gates: {
      soloLeadMin: 0.66,
      peakMin: 0.58,
    },
    pool: [
      { id: "lightning_bolt", label: "Lightning Bolt Flash", weight: 1.0, enabled: true, lifeSeconds: 0.65, fadeInRatio: 0.1, holdRatio: 0.38 },
      { id: "rose_bloom", label: "Rose Bloom Apparition", weight: 0.72, enabled: true, lifeSeconds: 1.35, fadeInRatio: 0.28, holdRatio: 0.62 },
      { id: "skull", label: "Skull Apparition", weight: 0.52, enabled: true, lifeSeconds: 1.1, fadeInRatio: 0.2, holdRatio: 0.54 },
      { id: "dancing_skeleton", label: "Dancing Skeleton Figure", weight: 0.35, enabled: true, lifeSeconds: 1.45, fadeInRatio: 0.24, holdRatio: 0.56 },
      { id: "bear_silhouette", label: "Bear-Like Silhouette", weight: 0.18, enabled: false, lifeSeconds: 1.6, fadeInRatio: 0.28, holdRatio: 0.5 },
    ],
  },

  audio: {
    fftSize: 2048,
    smoothingTimeConstant: 0.32,
    inputFloorMultiplier: 0.5,
    echoCancellation: false,
    noiseSuppression: false,
    autoGainControl: false,
    debugTransport: true,
    adaptiveNoiseFloor: {
      riseSeconds: 9.0,
      fallSeconds: 7.0,
      captureHeadroom: 0.03,
      bias: 0.012,
      activeAboveFloor: 0.018,
      signalCeiling: 0.2,
      burstRiseSuppress: 0.12,
    },
    manualBaseline: {
      learningSeconds: 2.0,
      minSamples: 25,
      floorPercentile: 0.3,
    },
    tuning: {
      micSensitivity: 2.0,
      noiseGate: 0.02,
      sustainThreshold: 0.03,
      activateThreshold: 0.05,
      deactivateThreshold: 0.02,
      holdTime: 650,
      fadeTime: 900,
      responseCurve: 1.15,
      motionScale: 0.08,
      baseFlow: 0.0,
      maxSpeed: 0.18,
      audioReactivity: 1.0,
      peakIntensity: 1.0,
      bassWeight: 1.0,
      midsWeight: 0.9,
      highsWeight: 0.65,
    },
  },

  blackout: {
    activeSignalThreshold: 0.02,
    holdSeconds: 0.8,
    fadeSeconds: 1.35,
    silenceStart: 0.72,
    silenceHard: 0.9,
    silenceFull: 0.975,
  },
};
