export const CONFIG = {
  buildTag: "dv-157-full-control-panel",
  devControls: {
    enabled: true,
  },
  modes: {
    names: {
      1: "Liquid Tie-Dye",
      2: "Mandala Bloom Fractal",
      3: "Liquid Tie-Dye (3)",
      4: "Liquid Tie-Dye (4)",
    },
    defaultMode: 1,
    autoCycleSeconds: 18,
    settingsByMode: {
      1: {
        micSensitivity: 1.0,
        noiseGate: 0.03,
        sustainThreshold: 0.09,
        activateThreshold: 0.34,
        deactivateThreshold: 0.2,
        holdTime: 90,
        fadeTime: 260,
        motionScale: 0.35,
        baseFlow: 0.02,
        responseCurve: 1.5,
        maxSpeed: 0.6,
        bassWeight: 0.26,
        midsWeight: 0.2,
        highsWeight: 0.1,
      },
      2: {
        micSensitivity: 0.85,
        noiseGate: 0.03,
        sustainThreshold: 0.085,
        activateThreshold: 0.3,
        deactivateThreshold: 0.18,
        holdTime: 110,
        fadeTime: 320,
        motionScale: 0.2,
        baseFlow: 0.01,
        responseCurve: 1.4,
        maxSpeed: 0.5,
        bassWeight: 0.22,
        midsWeight: 0.24,
        highsWeight: 0.14,
      },
      3: {
        micSensitivity: 1.05,
        noiseGate: 0.03,
        sustainThreshold: 0.095,
        activateThreshold: 0.33,
        deactivateThreshold: 0.19,
        holdTime: 85,
        fadeTime: 240,
        motionScale: 0.4,
        baseFlow: 0.02,
        responseCurve: 1.55,
        maxSpeed: 0.65,
        bassWeight: 0.28,
        midsWeight: 0.2,
        highsWeight: 0.1,
      },
      4: {
        micSensitivity: 1.1,
        noiseGate: 0.03,
        sustainThreshold: 0.1,
        activateThreshold: 0.35,
        deactivateThreshold: 0.21,
        holdTime: 80,
        fadeTime: 220,
        motionScale: 0.5,
        baseFlow: 0.03,
        responseCurve: 1.6,
        maxSpeed: 0.75,
        bassWeight: 0.3,
        midsWeight: 0.2,
        highsWeight: 0.1,
      },
    },
  },

  soloEvents: {
    enabled: false,
    baseSpawnChance: 0.015,
    cooldownSeconds: {
      min: 8,
      max: 18,
    },
    gates: {
      soloLeadMin: 0.66,
      peakMin: 0.58,
    },
    pool: [
      { id: "lightning_bolt", label: "Lightning Bolt Flash", weight: 1.0, enabled: true, lifeSeconds: 0.65, fadeInRatio: 0.1, holdRatio: 0.38 },
      { id: "rose_bloom", label: "Rose Bloom Apparition", weight: 0.72, enabled: true, lifeSeconds: 1.35, fadeInRatio: 0.28, holdRatio: 0.62 },
      { id: "skull", label: "Skull Apparition", weight: 0.52, enabled: true, lifeSeconds: 1.1, fadeInRatio: 0.2, holdRatio: 0.54 },
      { id: "dancing_skeleton", label: "Dancing Skeleton Figure", weight: 0.35, enabled: true, lifeSeconds: 1.45, fadeInRatio: 0.24, holdRatio: 0.56 },
      { id: "bear_silhouette", label: "Bear-Like Silhouette", weight: 0.18, enabled: false, lifeSeconds: 1.6, fadeInRatio: 0.28, holdRatio: 0.5 },
    ],
  },

  audio: {
    fftSize: 2048,
    smoothingTimeConstant: 0.52,
    echoCancellation: false,
    noiseSuppression: false,
    autoGainControl: false,
    debugTransport: true,
    adaptiveNoiseFloor: {
      riseSeconds: 9.0,
      fallSeconds: 7.0,
      captureHeadroom: 0.03,
      bias: 0.012,
      activeAboveFloor: 0.018,
      signalCeiling: 0.2,
      burstRiseSuppress: 0.12,
    },
    tuning: {
      micSensitivity: 1.0,
      noiseGate: 0.03,
      sustainThreshold: 0.09,
      activateThreshold: 0.34,
      deactivateThreshold: 0.2,
      holdTime: 90,
      fadeTime: 260,
      responseCurve: 1.5,
      bassWeight: 0.26,
      midsWeight: 0.2,
      highsWeight: 0.1,
    },
  },

  blackout: {
    activeSignalThreshold: 0.02,
    holdSeconds: 0.8,
    fadeSeconds: 1.35,
    silenceStart: 0.72,
    silenceHard: 0.9,
    silenceFull: 0.975,
  },
};
